services:
  mau-app-codigo:
    image: "{{ CONTAINER_REGISTRY_URL }}/codigo/mau-app:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      DEBUG: "true"
      PUBLIC_LOG_LEVEL: "debug"
    ports:
      - "3000"
    networks:
      - internal_net
      - caddy_net

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    entrypoint: ["/bin/sh", "/run/entrypoint.sh"]
    volumes:
      - /home/codigo/mau-app/data/pocketbase/pb_data:/pb_data
      - /home/codigo/mau-app/data/pocketbase/pb_public:/pb_public
      - /home/codigo/mau-app/data/pocketbase/pb_migrations:/pb_migrations
    networks:
      - internal_net
      - caddy_net
    secrets:
      - mau-app_pb_encryption_key
    configs:
      - source: mau-app_pocketbase_entrypoint
        target: /run/entrypoint.sh
        mode: 0755

secrets:
  mau-app_pb_encryption_key:
    external: true

configs:
  mau-app_pocketbase_entrypoint:
    file: /home/codigo/mau-app/bin/pocketbase/entrypoint.sh

networks:
  internal_net:
    driver: overlay
  caddy_net:
    external: true
