services:
  mau-app-codigo:
    image: "{{ CONTAINER_REGISTRY_URL }}/codigo/mau-app:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      ORIGIN: "{{ ORIGIN_CODIGO }}"
    networks:
      - internal_net
      - caddy_net

  mau-app-maumercado:
    image: "{{ CONTAINER_REGISTRY_URL }}/codigo/mau-app:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      ORIGIN: "{{ ORIGIN_MAUMERCADO }}"
    networks:
      - internal_net
      - caddy_net

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command:
      - --encryptionEnv
      - ENCRYPTION
    environment:
      ENCRYPTION: /run/secrets/encryption_key
    volumes:
      - /home/codigo/mau-app/data/pocketbase/pb_data:/pb_data
      - /home/codigo/mau-app/data/pocketbase/pb_public:/pb_public
      - /home/codigo/mau-app/data/pocketbase/pb_migrations:/pb_migrations
    networks:
      - internal_net
      - caddy_net
    secrets:
      - encryption_key

  typesense:
    image: typesense/typesense:26.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /home/codigo/mau-app/data/typesense:/data
    command:
      - --data-dir
      - /data
      - --api-key
      - ${TYPESENSE_API_KEY}
    environment:
      TYPESENSE_API_KEY: /run/secrets/typesense_api_key
    networks:
      - internal_net
      - caddy_net
    secrets:
      - typesense_api_key

secrets:
  encryption_key:
    name: mau-app_pb_encryption_key
    external: true
  typesense_api_key:
    name: mau-app_typesense_api_key
    external: true

networks:
  internal_net:
    driver: overlay
  caddy_net:
    external: true
